/**
 * @file maxmind_store.hpp
 * @brief Database storage engine for Maxora
 *
 * Provides static methods and global state management for the libmaxminddb connection.
 * Note: This class uses global static variables. It is designed for SA-MP / open.mp
 * architectures where script execution is largely single-threaded. If multi-threading
 * is introduced, mutexes will be required for thread-safety.
 */

#pragma once

#include <maxminddb.h>
#include <string>
#include <unordered_map>

namespace maxora
{
	/**
	 * @class MaxmindStore
	 * @brief A static utility class to manage the lifecycle of the MaxMind DB.
	 */
	class MaxmindStore
	{
	  public:
		/**
		 * @brief Loads a MaxMind database from the specified file path.
		 * @param filename The path to the `.mmdb` file.
		 * @return An integer handle > 0 if successful, or 0 on failure.
		 */
		static int LoadDB(const char* filename);

		/**
		 * @brief Unloads a specific MaxMind database and frees memory.
		 * @param handle The database handle.
		 * @return True if successful, false if the handle was invalid.
		 */
		static bool UnloadDB(int handle);

		/**
		 * @brief Unloads all currently loaded databases.
		 */
		static void UnloadAll();

		/**
		 * @brief Checks if a specific MaxMind database is currently loaded in memory.
		 * @param handle The database handle.
		 * @return True if loaded, false otherwise.
		 */
		static bool IsLoaded(int handle);

		/**
		 * @brief Gets the pointer to the underlying MaxMind database structure for a specific
		 * handle.
		 * @param handle The database handle.
		 * @return A pointer to the `MMDB_s` struct, or nullptr if the handle is invalid.
		 */
		static MMDB_s* GetDB(int handle);

		/**
		 * @brief Retrieves the last error message recorded by the plugin.
		 * @return A constant reference to the error string.
		 */
		static const std::string& GetLastError();

		/**
		 * @brief Sets a new error message to be retrieved by the AMX script later.
		 * @param err The error message to record.
		 */
		static void SetLastError(const std::string& err);

	  private:
		// Map holding active memory-mapped databases by their assigned integer handle.
		static std::unordered_map<int, MMDB_s> databases_;

		// Auto-incrementing counter to assign unique handle IDs (starts at 1).
		static int nextHandle_;

		// Buffer storing the last error message generated by the plugin operations.
		static std::string lastError_;
	};
} // namespace maxora
