/**
 * @file maxmind_store.hpp
 * @brief Database storage engine for Maxora
 *
 * Provides static methods and global state management for the libmaxminddb connection.
 * Note: This class uses global static variables. It is designed for SA-MP / open.mp
 * architectures where script execution is largely single-threaded. If multi-threading
 * is introduced, mutexes will be required for thread-safety.
 */

#pragma once

#include <maxminddb.h>
#include <string>

namespace maxora
{
	/**
	 * @class MaxmindStore
	 * @brief A static utility class to manage the lifecycle of the MaxMind DB.
	 */
	class MaxmindStore
	{
	  public:
		/**
		 * @brief Loads a MaxMind database from the specified file path.
		 * @param filename The path to the `.mmdb` file.
		 * @return True if the database was successfully loaded, false otherwise.
		 */
		static bool LoadDB(const char* filename);

		/**
		 * @brief Unloads the currently loaded MaxMind database and frees memory.
		 */
		static void UnloadDB();

		/**
		 * @brief Checks if a MaxMind database is currently loaded in memory.
		 * @return True if loaded, false otherwise.
		 */
		static bool IsLoaded();

		/**
		 * @brief Gets the pointer to the underlying MaxMind database structure.
		 * @return A pointer to the `MMDB_s` struct.
		 */
		static MMDB_s* GetDB();

		/**
		 * @brief Retrieves the last error message recorded by the plugin.
		 * @return A constant reference to the error string.
		 */
		static const std::string& GetLastError();

		/**
		 * @brief Sets a new error message to be retrieved by the AMX script later.
		 * @param err The error message to record.
		 */
		static void SetLastError(const std::string& err);

	  private:
		// The actual libmaxminddb structure holding the memory-mapped file or loaded data.
		static MMDB_s mmdb_;

		// Flag indicating whether mmdb_ contains valid, loaded data.
		static bool isLoaded_;

		// Buffer storing the last error message generated by the plugin operations.
		static std::string lastError_;
	};
} // namespace maxora
